language: objective-c
osx_image: xcode10
cache:
  directories:
  - Carthage
xcode_project: Moers.xcodeproj
xcode_scheme: Moers
before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
xcode_destination: platform='iOS Simulator', OS=12.0, name='iPhone X'
xcode_sdk: iphonesimulator12.0
