default_platform(:android)

platform :android do
  
  # Runs before all tasks
  before_all do
    ENV["SLACK_URL"]
  end

  desc "Increment version code (Build number)"
  lane :increment_version_code do
    gradle(
      project_dir: "..",
      task: ":moers-festival-android:incrementVersionCode",
      flags: "--no-configuration-cache"
    )
  end

  desc "Increment version (Version name)"
  lane :increment_version do |options|
    mode = options[:mode] || 'patch'

    if ['patch', 'minor', 'major'].include? mode
      UI.message "Incrementing Version: #{mode}"

      gradle(
        project_dir: "..",
        task: ":moers-festival-android:incrementVersion",
        flags: "--no-configuration-cache",
        properties: {
          "mode" => mode
        }
      )
    else
      UI.error("Unknown mode: #{mode}")
    end
  end

  desc "Runs all the tests"
  lane :test do
    gradle(
      project_dir: "..",
      task: ":moers-festival-android:test"
    )
  end

  desc "Build a debug APK"
  lane :debug_build do
    gradle(
      project_dir: "..",
      tasks: ["clean", ":moers-festival-android:assembleDebug"]
    )
  end

  desc "Build a signed release APK & deploy to slack"
  lane :slack_apk_build do
    gradle(
      project_dir: "..",
      tasks: ["clean", ":moers-festival-android:assembleRelease"],
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )
    upload_to_slack()
    slack(message: ":rocket: *Build Successful!* :rocket:")
  end

  desc "Upload APK to Slack channel"
  private_lane :upload_to_slack do |options|
    file_path = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    file_name = file_path.gsub(/\/.*\//,"")
    access_token = ENV["ACCESS_TOKEN"]
    channel_name = "deployments"

    sh "echo Uploading " + file_name + " to Slack"
    sh "curl https://slack.com/api/files.upload -F token=\"" + access_token + "\" -F channels=\"" + channel_name + "\" -F title=\"" + file_name + "\" -F filename=\"" + file_name + "\" -F file=@" + file_path
    slack(message: "Successful upload to Slack! :rocket:")
  end

  desc "Deploy a new version to internal track"
  lane :deploy_internal do |options|
    
    gradle(
      project_dir: "..",
      tasks: ["clean", ":moers-festival-android:bundleRelease"],
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )
    upload_to_play_store(track: 'internal')
    slack(message: "Successful deployment to beta track! :rocket:")
  end

  desc "Deploy a new version to beta track"
  lane :deploy_beta do |options|
    
    # upload_to_play_store(track: "beta")
    # slack(message: "Successful deployment to beta track! :rocket:")
  end

  desc "Deploy a new version to production track"
  lane :deploy_production do |options|
    gradle(
      project_dir: "..",
      tasks: ["clean", ":moers-festival-android:bundleRelease"],
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      }
    )

    upload_to_play_store()
    slack(message: "Successful deployment to production track! :rocket:")
  end

end
