[versions]

appcompat = "1.7.0"
compose = "1.7.1"
compose-compiler = "1.5.5"
compose-plugin = "1.5.12"
agp = "8.6.0"
android-minSdk = "24"
android-compileSdk = "34"
android-targetSdk = "34"
androidx-activityCompose = "1.9.2"
androidx-navigationCompose = "2.8.0"
androidx-viewmodelCompose = "2.8.5"
coreKtx = "1.13.1"
kotlin = "1.9.20"
koin = "3.5.3"
kotlinxCoroutinesAndroid = "1.8.0"
ktor = "2.3.8"
coil = "2.5.0"
kmmViewmodel = "1.0.0-ALPHA-14"
material = "1.12.0"
skie = "0.8.4"

sdk = "34"
minSdk = "21"
targetSdk = "34"
gradle = "7.3.0"
coroutinesAndroid = "1.6.4"
lifecycle = "2.5.0"
hilt = "2.42"
datastore = "1.0.0"
protobuf = "3.19.0"
retrofit = "2.9.0"
autofill = "1.1.0"
gms = "19.0.1"
room = "2.4.2"
gson = "2.9.0"
junit = "4.13.2"
androidXTest = "1.4.0"
testRunner = "1.4.0"
testJunit = "1.1.3"
truth = "1.4.0"
espresso = "3.4.0"
workRuntimeKtx = "2.9.1"
ksp = "2.0.0-1.0.24"
kmpNativeCoroutines = "1.0.0-ALPHA-33"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigationCompose" }
androidx-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-viewmodelCompose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
kmm-viewmodel = { module = "com.rickclephas.kmm:kmm-viewmodel-core", version.ref = "kmmViewmodel" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "gms" }
skie-annotations = { module = "co.touchlab.skie:configuration-annotations", version.ref = "skie" }
junit = { module = "junit:junit", version.ref = "junit" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room"}
room-paging = { module = "androidx.room:room-paging", version.ref = "room"}
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.prefer = "1.2.0" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-simplexml = { module = "com.squareup.retrofit2:converter-simplexml", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-mock = { module = "com.squareup.retrofit2:retrofit-mock", version.ref = "retrofit" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
compose-material3 = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha14" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version = "1.3.0-alpha01" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version = "1.1.1" }
google-maps-compose = { module = "com.google.maps.android:maps-compose", version = "2.5.3" }
google-play-services-maps = { module = "com.google.android.gms:play-services-maps", version = "18.0.2" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version = "0.24.13-rc" }

[plugins]
kmpNativeCoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "kmpNativeCoroutines" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }