# A list of devices you want to take the screenshots from
devices([
  "iPhone 17 Pro",
])

# A list of supported languages
languages([
    "en-US",  
    "de-DE",
])

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

override_status_bar(true)
localize_simulator(true)
dark_mode(true)
disable_slide_to_type(true)
skip_open_summary(true)
