# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end

default_platform(:ios)

platform :ios do
  setup_travis

  desc "Run All Unit Tests"
  lane :test do
    run_tests(scheme: "Moers",
              devices: ["iPhone X"])
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do

    increment_build_number_in_plist(target: 'Moers')
    increment_build_number_in_plist(target: 'MoersTests')
    increment_build_number_in_plist(target: 'MoersUITests')

    increment_build_number

    build_app(scheme: "Moers")
    upload_to_testflight


    slack(
      message: "Mein Moers Beta successfully released!",
      channel: "#mein-moers",
      payload: {
        "Build Date" => Time.new.to_s,
        "Built by" => "Fastlane",
      }
    )

  end

  desc "Creating a code signing certificate and provisioning profile"
  lane :provisioning do 
    
    produce(
      app_name: 'Mein Moers',
      language: 'German',
      app_version: '2.1',
      sku: 'de.okfn.niederrhein.moers.001'
    )

    cert

    sigh(force: true)

  end

  # --- Screenshots and Upload them to AppStore Connect ---

  desc "Take Screenshots and Upload them to AppStore Connect"
  lane :screenshots do
    take_screenshots
    upload_to_app_store
  end

  desc "Take Screenshots"
  lane :take_screenshots do
    snapshot
    frame_screenshots(path: "/screenshots")
  end

  desc "Create ipa"
  lane :build do
    increment_build_number_in_plist(target: 'Moers')
    increment_build_number_in_plist(target: 'MoersTests')
    increment_build_number_in_plist(target: 'MoersUITests')
    
    gym(options.merge(:export_xcargs => "-allowProvisioningUpdates"))
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

  desc "Provision, take screenshots, build and upload to App Store"
  lane :do_everything do
    provisioning
    screenshots
    build
    upload
  end

  error do |lane, exception|
    
    slack(
      message: exception.message,
      channel: "#mein-moers",
      success: false
    )

  end

end
