# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8 Plus",
  "iPhone Xs Max",
  "iPhone X",
  "iPad Pro (12.9-inch)"
])

# A list of supported languages
languages([
  "de-DE",
  "en-US"
])

# The name of the scheme which contains the UI Tests
# scheme "SchemeName"

# Where should the resulting screenshots be stored?
output_directory "./Fastlane/screenshots"

# Clears previous screenshots
clear_previous_screenshots true
