name: Release Android Version

on:
#  push:
#    branches: master
#    tags:
#      - v*
  workflow_dispatch:
    inputs:
      version_bump:
        type: choice
        required: true
        description: Android Version
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Version Bump
        run: |
          echo "Executing version bump: ${{ github.event.inputs.version_bump }}"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3    
      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > androidApp/Keystore.jks
          echo "storeFile=Keystore.jks" >> keystore.properties
          echo "keyAlias=$ANDROID_KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$ANDROID_KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }}
          ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play Config file
        run: |
          echo "$ANDROID_PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          ANDROID_PLAY_CONFIG_JSON: ${{ secrets.ANDROID_PLAY_CONFIG_JSON }}

      - name: Distribute app to Beta track 🚀
        run: bundle exec fastlane beta