// Canvas Registry - Maps device sizes to available Remotion compositions
// Each entry represents a canvas that can render screenshots for a specific device

import type { DeviceScreenshot } from "./apple-screenshot-sizes";

export interface CanvasEntry {
  id: string;
  deviceName: string;
  displayName: string;
  width: number;
  height: number;
  orientation: "portrait" | "landscape";
}

export interface CanvasRegistry {
  entries: CanvasEntry[];
}

const portraitOrient = "portrait" as const;
const landscapeOrient = "landscape" as const;

function createEntry(
  id: string,
  deviceName: string,
  displayName: string,
  width: number,
  height: number,
  orientation: "portrait" | "landscape",
): CanvasEntry {
  return { id, deviceName, displayName, width, height, orientation };
}

// =============================================================================
// Registry Entries
// =============================================================================

export const canvasRegistry: CanvasRegistry = {
  entries: [
    // iPhone 6.9" displays
    createEntry(
      "iphone-air-portrait",
      "iPhone Air",
      "iPhone Air (Portrait)",
      1260,
      2736,
      portraitOrient,
    ),
    createEntry(
      "iphone-air-landscape",
      "iPhone Air",
      "iPhone Air (Landscape)",
      2736,
      1260,
      landscapeOrient,
    ),
    createEntry(
      "iphone-17-pro-max-portrait",
      "iPhone 17 Pro Max",
      "iPhone 17 Pro Max (Portrait)",
      1260,
      2736,
      portraitOrient,
    ),
    createEntry(
      "iphone-17-pro-max-landscape",
      "iPhone 17 Pro Max",
      "iPhone 17 Pro Max (Landscape)",
      2736,
      1260,
      landscapeOrient,
    ),
    createEntry(
      "iphone-16-pro-max-portrait",
      "iPhone 16 Pro Max",
      "iPhone 16 Pro Max (Portrait)",
      1260,
      2736,
      portraitOrient,
    ),
    createEntry(
      "iphone-16-pro-max-landscape",
      "iPhone 16 Pro Max",
      "iPhone 16 Pro Max (Landscape)",
      2736,
      1260,
      landscapeOrient,
    ),
    createEntry(
      "iphone-16-plus-portrait",
      "iPhone 16 Plus",
      "iPhone 16 Plus (Portrait)",
      1260,
      2736,
      portraitOrient,
    ),
    createEntry(
      "iphone-16-plus-landscape",
      "iPhone 16 Plus",
      "iPhone 16 Plus (Landscape)",
      2736,
      1260,
      landscapeOrient,
    ),
    createEntry(
      "iphone-15-pro-max-portrait",
      "iPhone 15 Pro Max",
      "iPhone 15 Pro Max (Portrait)",
      1260,
      2736,
      portraitOrient,
    ),
    createEntry(
      "iphone-15-pro-max-landscape",
      "iPhone 15 Pro Max",
      "iPhone 15 Pro Max (Landscape)",
      2736,
      1260,
      landscapeOrient,
    ),
    createEntry(
      "iphone-15-plus-portrait",
      "iPhone 15 Plus",
      "iPhone 15 Plus (Portrait)",
      1260,
      2736,
      portraitOrient,
    ),
    createEntry(
      "iphone-15-plus-landscape",
      "iPhone 15 Plus",
      "iPhone 15 Plus (Landscape)",
      2736,
      1260,
      landscapeOrient,
    ),
    createEntry(
      "iphone-14-pro-max-portrait",
      "iPhone 14 Pro Max",
      "iPhone 14 Pro Max (Portrait)",
      1260,
      2736,
      portraitOrient,
    ),
    createEntry(
      "iphone-14-pro-max-landscape",
      "iPhone 14 Pro Max",
      "iPhone 14 Pro Max (Landscape)",
      2736,
      1260,
      landscapeOrient,
    ),

    // iPhone 6.5" displays
    createEntry(
      "iphone-14-plus-portrait",
      "iPhone 14 Plus",
      "iPhone 14 Plus (Portrait)",
      1284,
      2778,
      portraitOrient,
    ),
    createEntry(
      "iphone-14-plus-landscape",
      "iPhone 14 Plus",
      "iPhone 14 Plus (Landscape)",
      2778,
      1284,
      landscapeOrient,
    ),
    createEntry(
      "iphone-13-pro-max-portrait",
      "iPhone 13 Pro Max",
      "iPhone 13 Pro Max (Portrait)",
      1284,
      2778,
      portraitOrient,
    ),
    createEntry(
      "iphone-13-pro-max-landscape",
      "iPhone 13 Pro Max",
      "iPhone 13 Pro Max (Landscape)",
      2778,
      1284,
      landscapeOrient,
    ),
    createEntry(
      "iphone-12-pro-max-portrait",
      "iPhone 12 Pro Max",
      "iPhone 12 Pro Max (Portrait)",
      1284,
      2778,
      portraitOrient,
    ),
    createEntry(
      "iphone-12-pro-max-landscape",
      "iPhone 12 Pro Max",
      "iPhone 12 Pro Max (Landscape)",
      2778,
      1284,
      landscapeOrient,
    ),
    createEntry(
      "iphone-11-pro-max-portrait",
      "iPhone 11 Pro Max",
      "iPhone 11 Pro Max (Portrait)",
      1242,
      2688,
      portraitOrient,
    ),
    createEntry(
      "iphone-11-pro-max-landscape",
      "iPhone 11 Pro Max",
      "iPhone 11 Pro Max (Landscape)",
      2688,
      1242,
      landscapeOrient,
    ),
    createEntry(
      "iphone-11-portrait",
      "iPhone 11",
      "iPhone 11 (Portrait)",
      1242,
      2688,
      portraitOrient,
    ),
    createEntry(
      "iphone-11-landscape",
      "iPhone 11",
      "iPhone 11 (Landscape)",
      2688,
      1242,
      landscapeOrient,
    ),
    createEntry(
      "iphone-xs-max-portrait",
      "iPhone XS Max",
      "iPhone XS Max (Portrait)",
      1242,
      2688,
      portraitOrient,
    ),
    createEntry(
      "iphone-xs-max-landscape",
      "iPhone XS Max",
      "iPhone XS Max (Landscape)",
      2688,
      1242,
      landscapeOrient,
    ),
    createEntry(
      "iphone-xr-portrait",
      "iPhone XR",
      "iPhone XR (Portrait)",
      1242,
      2688,
      portraitOrient,
    ),
    createEntry(
      "iphone-xr-landscape",
      "iPhone XR",
      "iPhone XR (Landscape)",
      2688,
      1242,
      landscapeOrient,
    ),

    // iPhone 6.3" displays
    createEntry(
      "iphone-17-pro-portrait",
      "iPhone 17 Pro",
      "iPhone 17 Pro (Portrait)",
      1206,
      2622,
      portraitOrient,
    ),
    createEntry(
      "iphone-17-pro-landscape",
      "iPhone 17 Pro",
      "iPhone 17 Pro (Landscape)",
      2622,
      1206,
      landscapeOrient,
    ),
    createEntry(
      "iphone-17-portrait",
      "iPhone 17",
      "iPhone 17 (Portrait)",
      1179,
      2556,
      portraitOrient,
    ),
    createEntry(
      "iphone-17-landscape",
      "iPhone 17",
      "iPhone 17 (Landscape)",
      2556,
      1179,
      landscapeOrient,
    ),
    createEntry(
      "iphone-16-pro-portrait",
      "iPhone 16 Pro",
      "iPhone 16 Pro (Portrait)",
      1206,
      2622,
      portraitOrient,
    ),
    createEntry(
      "iphone-16-pro-landscape",
      "iPhone 16 Pro",
      "iPhone 16 Pro (Landscape)",
      2622,
      1206,
      landscapeOrient,
    ),
    createEntry(
      "iphone-16-portrait",
      "iPhone 16",
      "iPhone 16 (Portrait)",
      1179,
      2556,
      portraitOrient,
    ),
    createEntry(
      "iphone-16-landscape",
      "iPhone 16",
      "iPhone 16 (Landscape)",
      2556,
      1179,
      landscapeOrient,
    ),
    createEntry(
      "iphone-15-pro-portrait",
      "iPhone 15 Pro",
      "iPhone 15 Pro (Portrait)",
      1179,
      2556,
      portraitOrient,
    ),
    createEntry(
      "iphone-15-pro-landscape",
      "iPhone 15 Pro",
      "iPhone 15 Pro (Landscape)",
      2556,
      1179,
      landscapeOrient,
    ),
    createEntry(
      "iphone-15-portrait",
      "iPhone 15",
      "iPhone 15 (Portrait)",
      1179,
      2556,
      portraitOrient,
    ),
    createEntry(
      "iphone-15-landscape",
      "iPhone 15",
      "iPhone 15 (Landscape)",
      2556,
      1179,
      landscapeOrient,
    ),
    createEntry(
      "iphone-14-pro-portrait",
      "iPhone 14 Pro",
      "iPhone 14 Pro (Portrait)",
      1179,
      2556,
      portraitOrient,
    ),
    createEntry(
      "iphone-14-pro-landscape",
      "iPhone 14 Pro",
      "iPhone 14 Pro (Landscape)",
      2556,
      1179,
      landscapeOrient,
    ),

    // iPhone 6.1" displays
    createEntry(
      "iphone-17e-portrait",
      "iPhone 17e",
      "iPhone 17e (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-17e-landscape",
      "iPhone 17e",
      "iPhone 17e (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-16e-portrait",
      "iPhone 16e",
      "iPhone 16e (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-16e-landscape",
      "iPhone 16e",
      "iPhone 16e (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-14-portrait",
      "iPhone 14",
      "iPhone 14 (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-14-landscape",
      "iPhone 14",
      "iPhone 14 (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-13-pro-portrait",
      "iPhone 13 Pro",
      "iPhone 13 Pro (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-13-pro-landscape",
      "iPhone 13 Pro",
      "iPhone 13 Pro (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-13-portrait",
      "iPhone 13",
      "iPhone 13 (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-13-landscape",
      "iPhone 13",
      "iPhone 13 (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-13-mini-portrait",
      "iPhone 13 mini",
      "iPhone 13 mini (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-13-mini-landscape",
      "iPhone 13 mini",
      "iPhone 13 mini (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-12-pro-portrait",
      "iPhone 12 Pro",
      "iPhone 12 Pro (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-12-pro-landscape",
      "iPhone 12 Pro",
      "iPhone 12 Pro (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-12-portrait",
      "iPhone 12",
      "iPhone 12 (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-12-landscape",
      "iPhone 12",
      "iPhone 12 (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-12-mini-portrait",
      "iPhone 12 mini",
      "iPhone 12 mini (Portrait)",
      1170,
      2532,
      portraitOrient,
    ),
    createEntry(
      "iphone-12-mini-landscape",
      "iPhone 12 mini",
      "iPhone 12 mini (Landscape)",
      2532,
      1170,
      landscapeOrient,
    ),
    createEntry(
      "iphone-11-pro-portrait",
      "iPhone 11 Pro",
      "iPhone 11 Pro (Portrait)",
      1125,
      2436,
      portraitOrient,
    ),
    createEntry(
      "iphone-11-pro-landscape",
      "iPhone 11 Pro",
      "iPhone 11 Pro (Landscape)",
      2436,
      1125,
      landscapeOrient,
    ),
    createEntry(
      "iphone-xs-portrait",
      "iPhone XS",
      "iPhone XS (Portrait)",
      1125,
      2436,
      portraitOrient,
    ),
    createEntry(
      "iphone-xs-landscape",
      "iPhone XS",
      "iPhone XS (Landscape)",
      2436,
      1125,
      landscapeOrient,
    ),
    createEntry(
      "iphone-x-portrait",
      "iPhone X",
      "iPhone X (Portrait)",
      1125,
      2436,
      portraitOrient,
    ),
    createEntry(
      "iphone-x-landscape",
      "iPhone X",
      "iPhone X (Landscape)",
      2436,
      1125,
      landscapeOrient,
    ),

    // iPhone 5.5" displays
    createEntry(
      "iphone-8-plus-portrait",
      "iPhone 8 Plus",
      "iPhone 8 Plus (Portrait)",
      1242,
      2208,
      portraitOrient,
    ),
    createEntry(
      "iphone-8-plus-landscape",
      "iPhone 8 Plus",
      "iPhone 8 Plus (Landscape)",
      2208,
      1242,
      landscapeOrient,
    ),
    createEntry(
      "iphone-7-plus-portrait",
      "iPhone 7 Plus",
      "iPhone 7 Plus (Portrait)",
      1242,
      2208,
      portraitOrient,
    ),
    createEntry(
      "iphone-7-plus-landscape",
      "iPhone 7 Plus",
      "iPhone 7 Plus (Landscape)",
      2208,
      1242,
      landscapeOrient,
    ),
    createEntry(
      "iphone-6s-plus-portrait",
      "iPhone 6S Plus",
      "iPhone 6S Plus (Portrait)",
      1242,
      2208,
      portraitOrient,
    ),
    createEntry(
      "iphone-6s-plus-landscape",
      "iPhone 6S Plus",
      "iPhone 6S Plus (Landscape)",
      2208,
      1242,
      landscapeOrient,
    ),
    createEntry(
      "iphone-6-plus-portrait",
      "iPhone 6 Plus",
      "iPhone 6 Plus (Portrait)",
      1242,
      2208,
      portraitOrient,
    ),
    createEntry(
      "iphone-6-plus-landscape",
      "iPhone 6 Plus",
      "iPhone 6 Plus (Landscape)",
      2208,
      1242,
      landscapeOrient,
    ),

    // iPhone 4.7" displays
    createEntry(
      "iphone-se-3rd-gen-portrait",
      "iPhone SE (3rd generation)",
      "iPhone SE 3rd (Portrait)",
      750,
      1334,
      portraitOrient,
    ),
    createEntry(
      "iphone-se-3rd-gen-landscape",
      "iPhone SE (3rd generation)",
      "iPhone SE 3rd (Landscape)",
      1334,
      750,
      landscapeOrient,
    ),
    createEntry(
      "iphone-se-2nd-gen-portrait",
      "iPhone SE (2nd generation)",
      "iPhone SE 2nd (Portrait)",
      750,
      1334,
      portraitOrient,
    ),
    createEntry(
      "iphone-se-2nd-gen-landscape",
      "iPhone SE (2nd generation)",
      "iPhone SE 2nd (Landscape)",
      1334,
      750,
      landscapeOrient,
    ),
    createEntry(
      "iphone-8-portrait",
      "iPhone 8",
      "iPhone 8 (Portrait)",
      750,
      1334,
      portraitOrient,
    ),
    createEntry(
      "iphone-8-landscape",
      "iPhone 8",
      "iPhone 8 (Landscape)",
      1334,
      750,
      landscapeOrient,
    ),
    createEntry(
      "iphone-7-portrait",
      "iPhone 7",
      "iPhone 7 (Portrait)",
      750,
      1334,
      portraitOrient,
    ),
    createEntry(
      "iphone-7-landscape",
      "iPhone 7",
      "iPhone 7 (Landscape)",
      1334,
      750,
      landscapeOrient,
    ),
    createEntry(
      "iphone-6s-portrait",
      "iPhone 6S",
      "iPhone 6S (Portrait)",
      750,
      1334,
      portraitOrient,
    ),
    createEntry(
      "iphone-6s-landscape",
      "iPhone 6S",
      "iPhone 6S (Landscape)",
      1334,
      750,
      landscapeOrient,
    ),
    createEntry(
      "iphone-6-portrait",
      "iPhone 6",
      "iPhone 6 (Portrait)",
      750,
      1334,
      portraitOrient,
    ),
    createEntry(
      "iphone-6-landscape",
      "iPhone 6",
      "iPhone 6 (Landscape)",
      1334,
      750,
      landscapeOrient,
    ),

    // iPhone 4" displays
    createEntry(
      "iphone-se-1st-gen-portrait",
      "iPhone SE (1st generation)",
      "iPhone SE 1st (Portrait)",
      640,
      1136,
      portraitOrient,
    ),
    createEntry(
      "iphone-se-1st-gen-landscape",
      "iPhone SE (1st generation)",
      "iPhone SE 1st (Landscape)",
      1136,
      640,
      landscapeOrient,
    ),
    createEntry(
      "iphone-5s-portrait",
      "iPhone 5S",
      "iPhone 5S (Portrait)",
      640,
      1136,
      portraitOrient,
    ),
    createEntry(
      "iphone-5s-landscape",
      "iPhone 5S",
      "iPhone 5S (Landscape)",
      1136,
      640,
      landscapeOrient,
    ),
    createEntry(
      "iphone-5c-portrait",
      "iPhone 5C",
      "iPhone 5C (Portrait)",
      640,
      1136,
      portraitOrient,
    ),
    createEntry(
      "iphone-5c-landscape",
      "iPhone 5C",
      "iPhone 5C (Landscape)",
      1136,
      640,
      landscapeOrient,
    ),
    createEntry(
      "iphone-5-portrait",
      "iPhone 5",
      "iPhone 5 (Portrait)",
      640,
      1136,
      portraitOrient,
    ),
    createEntry(
      "iphone-5-landscape",
      "iPhone 5",
      "iPhone 5 (Landscape)",
      1136,
      640,
      landscapeOrient,
    ),

    // iPhone 3.5" displays
    createEntry(
      "iphone-4s-portrait",
      "iPhone 4S",
      "iPhone 4S (Portrait)",
      640,
      960,
      portraitOrient,
    ),
    createEntry(
      "iphone-4s-landscape",
      "iPhone 4S",
      "iPhone 4S (Landscape)",
      960,
      640,
      landscapeOrient,
    ),
    createEntry(
      "iphone-4-portrait",
      "iPhone 4",
      "iPhone 4 (Portrait)",
      640,
      960,
      portraitOrient,
    ),
    createEntry(
      "iphone-4-landscape",
      "iPhone 4",
      "iPhone 4 (Landscape)",
      960,
      640,
      landscapeOrient,
    ),

    // iPad 13" displays
    createEntry(
      "ipad-pro-13-m5-portrait",
      "iPad Pro (M5)",
      'iPad Pro 13" M5 (Portrait)',
      2064,
      2752,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-13-m5-landscape",
      "iPad Pro (M5)",
      'iPad Pro 13" M5 (Landscape)',
      2752,
      2064,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-13-m4-portrait",
      "iPad Pro (M4)",
      'iPad Pro 13" M4 (Portrait)',
      2064,
      2752,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-13-m4-landscape",
      "iPad Pro (M4)",
      'iPad Pro 13" M4 (Landscape)',
      2752,
      2064,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-13-gen6-portrait",
      "iPad Pro (6th generation)",
      'iPad Pro 13" Gen6 (Portrait)',
      2064,
      2752,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-13-gen6-landscape",
      "iPad Pro (6th generation)",
      'iPad Pro 13" Gen6 (Landscape)',
      2752,
      2064,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-13-gen5-portrait",
      "iPad Pro (5th generation)",
      'iPad Pro 13" Gen5 (Portrait)',
      2048,
      2732,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-13-gen5-landscape",
      "iPad Pro (5th generation)",
      'iPad Pro 13" Gen5 (Landscape)',
      2732,
      2048,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-13-gen4-portrait",
      "iPad Pro (4th generation)",
      'iPad Pro 13" Gen4 (Portrait)',
      2048,
      2732,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-13-gen4-landscape",
      "iPad Pro (4th generation)",
      'iPad Pro 13" Gen4 (Landscape)',
      2732,
      2048,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-13-gen3-portrait",
      "iPad Pro (3rd generation)",
      'iPad Pro 13" Gen3 (Portrait)',
      2048,
      2732,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-13-gen3-landscape",
      "iPad Pro (3rd generation)",
      'iPad Pro 13" Gen3 (Landscape)',
      2732,
      2048,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-13-gen1-portrait",
      "iPad Pro (1st generation)",
      'iPad Pro 13" Gen1 (Portrait)',
      2048,
      2732,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-13-gen1-landscape",
      "iPad Pro (1st generation)",
      'iPad Pro 13" Gen1 (Landscape)',
      2732,
      2048,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-13-m4-portrait",
      "iPad Air (M4)",
      'iPad Air 13" M4 (Portrait)',
      2064,
      2752,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-13-m4-landscape",
      "iPad Air (M4)",
      'iPad Air 13" M4 (Landscape)',
      2752,
      2064,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-13-m3-portrait",
      "iPad Air (M3)",
      'iPad Air 13" M3 (Portrait)',
      2064,
      2752,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-13-m3-landscape",
      "iPad Air (M3)",
      'iPad Air 13" M3 (Landscape)',
      2752,
      2064,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-13-m2-portrait",
      "iPad Air (M2)",
      'iPad Air 13" M2 (Portrait)',
      2064,
      2752,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-13-m2-landscape",
      "iPad Air (M2)",
      'iPad Air 13" M2 (Landscape)',
      2752,
      2064,
      landscapeOrient,
    ),

    // iPad 12.9" displays
    createEntry(
      "ipad-pro-12-9-gen2-portrait",
      "iPad Pro (2nd generation)",
      'iPad Pro 12.9" Gen2 (Portrait)',
      2048,
      2732,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-12-9-gen2-landscape",
      "iPad Pro (2nd generation)",
      'iPad Pro 12.9" Gen2 (Landscape)',
      2732,
      2048,
      landscapeOrient,
    ),

    // iPad 11" displays
    createEntry(
      "ipad-pro-11-m5-portrait",
      'iPad Pro 11" (M5)',
      'iPad Pro 11" M5 (Portrait)',
      1488,
      2266,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-11-m5-landscape",
      'iPad Pro 11" (M5)',
      'iPad Pro 11" M5 (Landscape)',
      2266,
      1488,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-11-m4-portrait",
      'iPad Pro 11" (M4)',
      'iPad Pro 11" M4 (Portrait)',
      1488,
      2266,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-11-m4-landscape",
      'iPad Pro 11" (M4)',
      'iPad Pro 11" M4 (Landscape)',
      2266,
      1488,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-11-gen4-portrait",
      'iPad Pro 11" (4th generation)',
      'iPad Pro 11" Gen4 (Portrait)',
      1668,
      2388,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-11-gen4-landscape",
      'iPad Pro 11" (4th generation)',
      'iPad Pro 11" Gen4 (Landscape)',
      2388,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-11-gen3-portrait",
      'iPad Pro 11" (3rd generation)',
      'iPad Pro 11" Gen3 (Portrait)',
      1668,
      2388,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-11-gen3-landscape",
      'iPad Pro 11" (3rd generation)',
      'iPad Pro 11" Gen3 (Landscape)',
      2388,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-11-gen2-portrait",
      'iPad Pro 11" (2nd generation)',
      'iPad Pro 11" Gen2 (Portrait)',
      1668,
      2388,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-11-gen2-landscape",
      'iPad Pro 11" (2nd generation)',
      'iPad Pro 11" Gen2 (Landscape)',
      2388,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-pro-11-gen1-portrait",
      'iPad Pro 11" (1st generation)',
      'iPad Pro 11" Gen1 (Portrait)',
      1668,
      2388,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-11-gen1-landscape",
      'iPad Pro 11" (1st generation)',
      'iPad Pro 11" Gen1 (Landscape)',
      2388,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-11-m4-portrait",
      'iPad Air 11" (M4)',
      'iPad Air 11" M4 (Portrait)',
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-11-m4-landscape",
      'iPad Air 11" (M4)',
      'iPad Air 11" M4 (Landscape)',
      2360,
      1640,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-11-m3-portrait",
      'iPad Air 11" (M3)',
      'iPad Air 11" M3 (Portrait)',
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-11-m3-landscape",
      'iPad Air 11" (M3)',
      'iPad Air 11" M3 (Landscape)',
      2360,
      1640,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-11-m2-portrait",
      'iPad Air 11" (M2)',
      'iPad Air 11" M2 (Portrait)',
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-11-m2-landscape",
      'iPad Air 11" (M2)',
      'iPad Air 11" M2 (Landscape)',
      2360,
      1640,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-11-gen5-portrait",
      'iPad Air 11" (5th generation)',
      'iPad Air 11" Gen5 (Portrait)',
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-11-gen5-landscape",
      'iPad Air 11" (5th generation)',
      'iPad Air 11" Gen5 (Landscape)',
      2360,
      1640,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-11-gen4-portrait",
      'iPad Air 11" (4th generation)',
      'iPad Air 11" Gen4 (Portrait)',
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-11-gen4-landscape",
      'iPad Air 11" (4th generation)',
      'iPad Air 11" Gen4 (Landscape)',
      2360,
      1640,
      landscapeOrient,
    ),
    createEntry(
      "ipad-10-gen-portrait",
      "iPad (10th generation)",
      "iPad 10th Gen (Portrait)",
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-10-gen-landscape",
      "iPad (10th generation)",
      "iPad 10th Gen (Landscape)",
      2360,
      1640,
      landscapeOrient,
    ),
    createEntry(
      "ipad-mini-a17-pro-portrait",
      "iPad mini (A17 Pro)",
      "iPad mini A17 Pro (Portrait)",
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-mini-a17-pro-landscape",
      "iPad mini (A17 Pro)",
      "iPad mini A17 Pro (Landscape)",
      2360,
      1640,
      landscapeOrient,
    ),
    createEntry(
      "ipad-mini-6-portrait",
      "iPad mini (6th generation)",
      "iPad mini 6th Gen (Portrait)",
      1640,
      2360,
      portraitOrient,
    ),
    createEntry(
      "ipad-mini-6-landscape",
      "iPad mini (6th generation)",
      "iPad mini 6th Gen (Landscape)",
      2360,
      1640,
      landscapeOrient,
    ),

    // iPad 10.5" displays
    createEntry(
      "ipad-pro-10-5-portrait",
      'iPad Pro 10.5"',
      'iPad Pro 10.5" (Portrait)',
      1668,
      2224,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-10-5-landscape",
      'iPad Pro 10.5"',
      'iPad Pro 10.5" (Landscape)',
      2224,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-3-portrait",
      "iPad Air (3rd generation)",
      "iPad Air 3rd Gen (Portrait)",
      1668,
      2224,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-3-landscape",
      "iPad Air (3rd generation)",
      "iPad Air 3rd Gen (Landscape)",
      2224,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-9-portrait",
      "iPad (9th generation)",
      "iPad 9th Gen (Portrait)",
      1668,
      2224,
      portraitOrient,
    ),
    createEntry(
      "ipad-9-landscape",
      "iPad (9th generation)",
      "iPad 9th Gen (Landscape)",
      2224,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-8-portrait",
      "iPad (8th generation)",
      "iPad 8th Gen (Portrait)",
      1668,
      2224,
      portraitOrient,
    ),
    createEntry(
      "ipad-8-landscape",
      "iPad (8th generation)",
      "iPad 8th Gen (Landscape)",
      2224,
      1668,
      landscapeOrient,
    ),
    createEntry(
      "ipad-7-portrait",
      "iPad (7th generation)",
      "iPad 7th Gen (Portrait)",
      1668,
      2224,
      portraitOrient,
    ),
    createEntry(
      "ipad-7-landscape",
      "iPad (7th generation)",
      "iPad 7th Gen (Landscape)",
      2224,
      1668,
      landscapeOrient,
    ),

    // iPad 9.7" displays
    createEntry(
      "ipad-pro-9-7-portrait",
      'iPad Pro 9.7"',
      'iPad Pro 9.7" (Portrait)',
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-pro-9-7-landscape",
      'iPad Pro 9.7"',
      'iPad Pro 9.7" (Landscape)',
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-portrait",
      "iPad Air",
      "iPad Air (Portrait)",
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-landscape",
      "iPad Air",
      "iPad Air (Landscape)",
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-air-2-portrait",
      "iPad Air 2",
      "iPad Air 2 (Portrait)",
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-air-2-landscape",
      "iPad Air 2",
      "iPad Air 2 (Landscape)",
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-portrait",
      "iPad",
      "iPad (Portrait)",
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-landscape",
      "iPad",
      "iPad (Landscape)",
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-2-portrait",
      "iPad 2",
      "iPad 2 (Portrait)",
      768,
      1024,
      portraitOrient,
    ),
    createEntry(
      "ipad-2-landscape",
      "iPad 2",
      "iPad 2 (Landscape)",
      1024,
      768,
      landscapeOrient,
    ),
    createEntry(
      "ipad-6-portrait",
      "iPad (6th generation)",
      "iPad 6th Gen (Portrait)",
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-6-landscape",
      "iPad (6th generation)",
      "iPad 6th Gen (Landscape)",
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-5-portrait",
      "iPad (5th generation)",
      "iPad 5th Gen (Portrait)",
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-5-landscape",
      "iPad (5th generation)",
      "iPad 5th Gen (Landscape)",
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-4-portrait",
      "iPad (4th generation)",
      "iPad 4th Gen (Portrait)",
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-4-landscape",
      "iPad (4th generation)",
      "iPad 4th Gen (Landscape)",
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-3-portrait",
      "iPad (3rd generation)",
      "iPad 3rd Gen (Portrait)",
      1536,
      2048,
      portraitOrient,
    ),
    createEntry(
      "ipad-3-landscape",
      "iPad (3rd generation)",
      "iPad 3rd Gen (Landscape)",
      2048,
      1536,
      landscapeOrient,
    ),
    createEntry(
      "ipad-mini-5-portrait",
      "iPad mini (5th generation)",
      "iPad mini 5th Gen (Portrait)",
      768,
      1024,
      portraitOrient,
    ),
    createEntry(
      "ipad-mini-5-landscape",
      "iPad mini (5th generation)",
      "iPad mini 5th Gen (Landscape)",
      1024,
      768,
      landscapeOrient,
    ),
    createEntry(
      "ipad-mini-4-portrait",
      "iPad mini 4",
      "iPad mini 4 (Portrait)",
      768,
      1024,
      portraitOrient,
    ),
    createEntry(
      "ipad-mini-4-landscape",
      "iPad mini 4",
      "iPad mini 4 (Landscape)",
      1024,
      768,
      landscapeOrient,
    ),
    createEntry(
      "ipad-mini-3-portrait",
      "iPad mini 3",
      "iPad mini 3 (Portrait)",
      768,
      1024,
      portraitOrient,
    ),
    createEntry(
      "ipad-mini-3-landscape",
      "iPad mini 3",
      "iPad mini 3 (Landscape)",
      1024,
      768,
      landscapeOrient,
    ),
    createEntry(
      "ipad-mini-2-portrait",
      "iPad mini 2",
      "iPad mini 2 (Portrait)",
      768,
      1024,
      portraitOrient,
    ),
    createEntry(
      "ipad-mini-2-landscape",
      "iPad mini 2",
      "iPad mini 2 (Landscape)",
      1024,
      768,
      landscapeOrient,
    ),

    // Apple Watch (portrait only)
    createEntry(
      "apple-watch-ultra-3-portrait",
      "Ultra 3",
      "Apple Watch Ultra 3 (Portrait)",
      422,
      514,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-ultra-2-portrait",
      "Ultra 2",
      "Apple Watch Ultra 2 (Portrait)",
      410,
      502,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-ultra-portrait",
      "Ultra",
      "Apple Watch Ultra (Portrait)",
      410,
      502,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-11-portrait",
      "Series 11",
      "Apple Watch Series 11 (Portrait)",
      416,
      496,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-10-portrait",
      "Series 10",
      "Apple Watch Series 10 (Portrait)",
      416,
      496,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-9-portrait",
      "Series 9",
      "Apple Watch Series 9 (Portrait)",
      396,
      484,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-8-portrait",
      "Series 8",
      "Apple Watch Series 8 (Portrait)",
      396,
      484,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-7-portrait",
      "Series 7",
      "Apple Watch Series 7 (Portrait)",
      396,
      484,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-6-portrait",
      "Series 6",
      "Apple Watch Series 6 (Portrait)",
      368,
      448,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-5-portrait",
      "Series 5",
      "Apple Watch Series 5 (Portrait)",
      368,
      448,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-4-portrait",
      "Series 4",
      "Apple Watch Series 4 (Portrait)",
      368,
      448,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-se-3-portrait",
      "SE 3",
      "Apple Watch SE 3 (Portrait)",
      368,
      448,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-se-portrait",
      "SE",
      "Apple Watch SE (Portrait)",
      368,
      448,
      portraitOrient,
    ),
    createEntry(
      "apple-watch-series-3-portrait",
      "Series 3",
      "Apple Watch Series 3 (Portrait)",
      312,
      390,
      portraitOrient,
    ),

    // Mac
    createEntry(
      "mac-1280x800",
      "Mac",
      "Mac 1280x800",
      1280,
      800,
      landscapeOrient,
    ),
    createEntry(
      "mac-1440x900",
      "Mac",
      "Mac 1440x900",
      1440,
      900,
      landscapeOrient,
    ),
    createEntry(
      "mac-2560x1600",
      "Mac",
      "Mac 2560x1600",
      2560,
      1600,
      landscapeOrient,
    ),
    createEntry(
      "mac-2880x1800",
      "Mac",
      "Mac 2880x1800",
      2880,
      1800,
      landscapeOrient,
    ),

    // Apple TV
    createEntry(
      "apple-tv-1080p",
      "Apple TV",
      "Apple TV 1080p",
      1920,
      1080,
      landscapeOrient,
    ),
    createEntry(
      "apple-tv-4k",
      "Apple TV",
      "Apple TV 4K",
      3840,
      2160,
      landscapeOrient,
    ),

    // Apple Vision Pro
    createEntry(
      "apple-vision-pro",
      "Apple Vision Pro",
      "Apple Vision Pro",
      3840,
      2160,
      landscapeOrient,
    ),
  ],
};

// =============================================================================
// Lookup Functions
// =============================================================================

export function findCanvasByDevice(
  device: DeviceScreenshot,
  orientation: "portrait" | "landscape" = "portrait",
): CanvasEntry | undefined {
  return canvasRegistry.entries.find(
    (e) => e.deviceName === device.name && e.orientation === orientation,
  );
}

export function findCanvasByDimensions(
  width: number,
  height: number,
  orientation?: "portrait" | "landscape",
): CanvasEntry | undefined {
  return canvasRegistry.entries.find((e) => {
    if (orientation && e.orientation !== orientation) return false;
    return e.width === width && e.height === height;
  });
}

export function getAllCanvasEntries(): CanvasEntry[] {
  return canvasRegistry.entries;
}

export function getCanvasEntryById(id: string): CanvasEntry | undefined {
  return canvasRegistry.entries.find((e) => e.id === id);
}

export function getCanvasesByDeviceName(deviceName: string): CanvasEntry[] {
  return canvasRegistry.entries.filter((e) => e.deviceName === deviceName);
}

export function getCanvasesByOrientation(
  orientation: "portrait" | "landscape",
): CanvasEntry[] {
  return canvasRegistry.entries.filter((e) => e.orientation === orientation);
}
